### PR TITLE
Add GitHub actions based CI suite

### PR DESCRIPTION
**Pull request by codingjoe**
Hi @KevinBrolly,

I took the liberty to invest some time and  get a GitHub action based CI suite running.  GH actions don't run before you being merged, but you can see the output here:
https://github.com/codingjoe/heroku-geo-buildpack/actions/runs/133759304

I did however not add tests for the cedar-14, since they don't pass on master.

I also added shellcheck and fixed all the issues it found and went on adding more tests. It's in separate commits.

Anyhow, let me know what you think.

Best,
Joe

### CODE REVIEW

**Comment by KevinBrolly** [comment]
Hey @codingjoe thank you for the huge effort, adding shellcheck and Github Actions for CI is great. Happy to get this merged but could you split out the addition of the `.editorconfig` file out into its own PR first? I am not against the idea of the `.editorconfig` in principle but if we were going to add it I think it would be better as a separate PR since it is not directly related to getting CI setup.

**Comment by codingjoe** [comment]
Hi @KevinBrolly sure thing. It's done #10 holds the editor config file and I removed it this change set. I can also split more things out, if that helps you to merge things faster.

**Comment by codingjoe** [comment]
BTW, I could also add a release workflow, that automatically pushes new binaries to S3. All you'd need to do is set secrets on the GitHub repo. I wanted to start with CI, but CD might be a great improvement. Especially for a buildpack that shouldn't eat up too much of your time. Let me know if that would be a welcome addition.

**Comment by KevinBrolly** [comment]
Looks great, thanks for this @codingjoe - A release workflow would be great, anything that makes building/distributing new binaries is very welcome.

**Pull request merged**
